// Usage: node memory/report.ts
import { readFileSync, writeFileSync } from 'node:fs';
import { environmentList, type environment } from '../common/environment.ts';
import type { MemoryScenario, Target } from './worker.ts';

export interface MemoryResults {
  command: string;
  environment: ReturnType<typeof environment>;
  method: { rounds: number; nodeFlags: string; seed: number; samplesPerCall: number };
  unit: 'bytes';
  measurements: Array<{
    library: string;
    target: Target;
    scenario: MemoryScenario;
    rounds: Array<{ bytes?: number; allocated?: number; result?: number; temporary?: number }>;
    mean: { bytes?: number; allocated?: number; result?: number; temporary?: number };
  }>;
}

const kb = (bytes: number) => `${(bytes / 1024).toLocaleString('en-US', { maximumFractionDigits: Math.abs(bytes) < 10 * 1024 ? 1 : 0 })} KB`;

const NAMES = {
  api: 'API response (100 users, 2,104 keys)',
  small: 'Small object (8 keys)',
  unique: 'Object with 1,000 unique keys',
} as const;

export function report() {
  const data: MemoryResults = JSON.parse(readFileSync(new URL('../results/memory.json', import.meta.url), 'utf8'));
  const { rounds, nodeFlags, samplesPerCall } = data.method;
  const find = (target: Target | undefined, scenario: MemoryScenario) => data.measurements.filter((m) => m.scenario === scenario && (!target || m.target === target));
  const cell = (m: MemoryResults['measurements'][number], key: 'bytes' | 'allocated' | 'result' | 'temporary') => kb(m.mean[key]!);
  const runs = (m: MemoryResults['measurements'][number], key: 'bytes' | 'allocated') => m.rounds.map((r) => kb(r[key]!)).join(', ');

  const sections = [
    [
      '## Loading the library',
      '',
      'Heap used by importing the library (its file in `libraries/`), before converting anything.',
      '',
      `| Library | Heap | Runs |`,
      '| --- | ---: | ---: |',
      ...find(undefined, 'module')
        .sort((a, b) => a.mean.bytes! - b.mean.bytes!)
        .map((m) => `| ${m.library} | ${cell(m, 'bytes')} | ${runs(m, 'bytes')} |`),
    ].join('\n'),
  ];
  for (const target of ['camel', 'snake'] as const) {
    for (const scenario of ['api', 'small', 'unique'] as const) {
      sections.push(
        [
          `## ${NAMES[scenario]} to ${target}: one call`,
          '',
          '| Library | Allocated | Result | Temporary | Allocated in each run |',
          '| --- | ---: | ---: | ---: | ---: |',
          ...find(target, scenario)
            .sort((a, b) => a.mean.allocated! - b.mean.allocated!)
            .map((m) => `| ${m.library} | ${cell(m, 'allocated')} | ${cell(m, 'result')} | ${cell(m, 'temporary')} | ${runs(m, 'allocated')} |`),
        ].join('\n'),
      );
    }
    sections.push(
      [
        `## Kept after converting 256,000 unique keys to ${target}`,
        '',
        'Heap still used after converting the 256 objects of the pool of unique keys and dropping the results. Values under 10 KB are the noise of the measurement.',
        '',
        '| Library | Kept | Runs |',
        '| --- | ---: | ---: |',
        ...find(target, 'retained')
          .sort((a, b) => a.mean.bytes! - b.mean.bytes!)
          .map((m) => `| ${m.library} | ${cell(m, 'bytes')} | ${runs(m, 'bytes')} |`),
      ].join('\n'),
    );
  }
  const header = [
    `Generated by \`${data.command}\`, on Node.js only (it needs \`--expose-gc\`). Each measurement runs in a new process, ${rounds} times in a shuffled order: \`node ${nodeFlags} memory/worker.ts <library> <camel|snake> <scenario>\`, which can be run alone to check it. The tables show the mean of the ${rounds} runs, and each run.`,
    '',
    `- **Allocated**: heap allocated by one call, the median of ${samplesPerCall} calls, with a garbage collection before each one and none during it.`,
    '- **Result**: the part of it that is the converted object. **Temporary**: the rest, garbage left by the call.',
    '- **Kept**: heap still used after the calls, like a cache kept between calls.',
    '',
    'Every run, with the samples of every call, is in [`memory.json`](./memory.json), and `node memory/report.ts` writes this file from it.',
    '',
    environmentList(data.environment),
  ].join('\n');
  writeFileSync(new URL('../results/memory.md', import.meta.url), `${header}\n\n${sections.join('\n\n')}\n`);
}

if (import.meta.main) report();
