// Usage: node speed/report.ts [node|bun|deno]
import { readFileSync, writeFileSync } from 'node:fs';
import { environmentList, type environment } from '../common/environment.ts';
import { CASES, keysLibraries, type Case } from '../libraries/index.ts';
import { caseScenarioName, KINDS, type Kind } from './scenarios.ts';

export interface Round {
  median: number;
  p99: number;
  rme: number;
  samples: number;
}

export interface SpeedResults {
  command: string;
  environment: ReturnType<typeof environment>;
  method: { rounds: number; time: number; warmupTime: number };
  unit: 'ms';
  scenarios: Array<{
    name: string;
    unsupported: string[];
    wrongOutput: string[];
    libraries: Record<string, { rounds: Round[]; mean: { median: number; p99: number } }>;
  }>;
}

const format = (ms: number) => (ms >= 1 ? `${ms.toFixed(2)} ms` : `${(ms * 1000).toFixed(2)} µs`);

type Scenario = SpeedResults['scenarios'][number];

function sorted(scenario: Scenario) {
  return Object.entries(scenario.libraries)
    .map(([library, { rounds, mean }]) => ({ library, mean, rounds, min: Math.min(...rounds.map((r) => r.median)), max: Math.max(...rounds.map((r) => r.median)) }))
    .sort((a, b) => a.mean.median - b.mean.median);
}

// Ties: libraries whose medians in the rounds overlap with the fastest's
function fastest(scenario: Scenario): Set<string> {
  const rows = sorted(scenario);
  return new Set(rows.filter((row) => row.min <= rows[0].max).map((row) => row.library));
}

function scenarioTable(scenario: Scenario, rounds: number): string {
  const rows = sorted(scenario);
  const best = fastest(scenario);
  return [
    `### ${scenario.name}`,
    '',
    `| Library | Median | ${Array.from({ length: rounds }, (_, i) => `Round ${i + 1}`).join(' | ')} | p99 | Relative |`,
    `| --- | ---: |${' ---: |'.repeat(rounds)} ---: | ---: |`,
    ...rows.map((row) => {
      const name = best.has(row.library) ? `**${row.library}**` : row.library;
      return `| ${name} | ${format(row.mean.median)} | ${row.rounds.map((r) => format(r.median)).join(' | ')} | ${format(row.mean.p99)} | ${(row.mean.median / rows[0].mean.median).toFixed(2)}x |`;
    }),
    ...(scenario.wrongOutput.length ? ['', `Not measured (unexpected output): ${scenario.wrongOutput.join(', ')}`] : []),
    ...(scenario.unsupported.length ? ['', `Don't convert keys to this case: ${scenario.unsupported.join(', ')}`] : []),
  ].join('\n');
}

function caseTable(kind: Kind, byName: Map<string, Scenario>): string {
  const names = keysLibraries.map((library) => library.name);
  const lines = (Object.keys(CASES) as Case[]).map((target) => {
    const scenario = byName.get(caseScenarioName(kind, target))!;
    const best = fastest(scenario);
    const cells = names.map((library) => {
      if (scenario.unsupported.includes(library)) return '❌';
      if (scenario.wrongOutput.includes(library)) return '⚠️';
      const value = format(scenario.libraries[library].mean.median);
      return best.has(library) ? `**${value}**` : value;
    });
    return `| ${target} (\`${CASES[target]}\`) | ${cells.join(' | ')} |`;
  });
  return [`### ${KINDS[kind]}`, '', `| Case | ${names.join(' | ')} |`, `| --- |${' ---: |'.repeat(names.length)}`, ...lines].join('\n');
}

export function report(runtime: string) {
  const data: SpeedResults = JSON.parse(readFileSync(new URL(`../results/speed-${runtime}.json`, import.meta.url), 'utf8'));
  const { rounds, time, warmupTime } = data.method;
  const byName = new Map(data.scenarios.map((scenario) => [scenario.name, scenario]));
  const content = [
    `Generated by \`${data.command}\`. Each library runs for ${time / 1000}s (after ${warmupTime / 1000}s of warmup) in each of ${rounds} rounds, and the order of the libraries changes between rounds. Median is the mean of the medians of the ${rounds} rounds, the time of one iteration; lower is faster. In **bold**: the fastest, and any library whose medians in the ${rounds} rounds overlap with the fastest's (a tie). ❌: the library doesn't convert keys to that case. ⚠️: it returned an unexpected output, so it was not measured.`,
    `Every round is in [\`speed-${runtime}.json\`](./speed-${runtime}.json), and \`node speed/report.ts ${runtime}\` writes this file from it.`,
    environmentList(data.environment),
    '## By case',
    'snake_case keys are converted to camel and pascal, and camelCase keys to the other cases. The rounds of each cell are in the tables below.',
    caseTable('repeated', byName),
    caseTable('unique', byName),
    '## All scenarios',
    ...data.scenarios.map((scenario) => scenarioTable(scenario, rounds)),
  ].join('\n\n');
  writeFileSync(new URL(`../results/speed-${runtime}.md`, import.meta.url), `${content}\n`);
}

if (import.meta.main) report(process.argv[2] ?? 'node');
