import { writeFileSync } from 'node:fs';
import { gzipSync } from 'node:zlib';
import { build } from 'esbuild';
import { environment, environmentList } from '../common/environment.ts';

const entries: Record<string, string> = {
  caseparser: `export { toCamel, toSnake } from '../../dist/index.js';`,
  'caseparser@5.1.0': `export { toCamel, toSnake } from 'caseparser-5.1.0';`,
  'change-case': `export { camelCase, snakeCase } from 'change-case/keys';`,
  'camelcase-keys + snakecase-keys': `export { default as camelcaseKeys } from 'camelcase-keys'; export { default as snakecaseKeys } from 'snakecase-keys';`,
  humps: `export { camelizeKeys, decamelizeKeys } from 'humps';`,
  'es-toolkit': `export { toCamelCaseKeys, toSnakeCaseKeys } from 'es-toolkit/object';`,
  'caseparser (the whole package)': `export * from '../../dist/index.js';`,
  'caseparser@5.1.0 (the whole package)': `export * from 'caseparser-5.1.0';`,
};

async function size(contents: string) {
  const result = await build({
    stdin: { contents, resolveDir: import.meta.dirname, loader: 'js' },
    bundle: true,
    minify: true,
    format: 'esm',
    platform: 'browser',
    write: false,
    logLevel: 'silent',
  });
  const code = result.outputFiles[0].contents;
  return { minified: code.length, gzipped: gzipSync(code, { level: 9 }).length };
}

const results: Record<string, { entry: string; minified: number; gzipped: number }> = {};
for (const [name, entry] of Object.entries(entries)) results[name] = { entry, ...(await size(entry)) };

const env = environment();
writeFileSync(new URL('../results/size.json', import.meta.url), `${JSON.stringify({ command: 'pnpm size', environment: env, unit: 'bytes', results }, null, 2)}\n`);
const bytes = (value: number) => `${value.toLocaleString('en-US')} B`;
const content = [
  'Generated by `pnpm size`. Size of the functions that convert keys to camelCase and snake_case, bundled with esbuild (minified, tree-shaken, with their dependencies), then gzipped. What each bundle imports is in [`size.json`](./size.json).',
  '',
  environmentList(env),
  '',
  '| Library | Minified | Gzipped |',
  '| --- | ---: | ---: |',
  ...Object.entries(results).map(([name, { minified, gzipped }]) => `| ${name} | ${bytes(minified)} | ${bytes(gzipped)} |`),
  '',
].join('\n');
writeFileSync(new URL('../results/size.md', import.meta.url), content);
console.log(content);
